### ISSUE TITLE
добавить автоматическую генерацию серииника и заполнения поля current quantity из initial quantity по кнопке read

### ISSUE THREAD

**Issue by azumi-san** [djbios/CartridgeWriter#1]
скорее всего, в фаил CartridgeWriter.xaml.cs
нужно добавить
//Generate a random number as new serial number 
private void cmdGenerate_Click(object sender, RoutedEventArgs e) 
{ 
Random zufall = new Random(); 
int number = zufall.Next(10000000, 99999999); 
txtSerialNumberChangeTo.Text = number.ToString() + ",0"; 
} 

//Automatically change the current quantity value to the inital quantity value 
private void txtInitialQuantityChangeTo_TextChanged(object sender, TextChangedEventArgs e) 
{ 
txtCurrentQuantityChangeTo.Text = txtInitialQuantityChangeTo.Text; 
}

**Comment by djbios** [comment]
Генерация серийника - отдельная кнопка?

**Comment by azumi-san** [comment]
> @azumi-san Генерация серийника - отдельная кнопка?

не, по нажатию кнопки read щас поля заполняются так, что слева то, что в чипе, а справа - что запишется.
нужно чтобы в том поле справа появлялся новыи серииник.
чтоб юзер мог тупо нажать на запись и не думать.

с количеством пластмассы та же история.
